// app/head.js
export default function Head() {
  return (
    <>
      <title>Canuck Mall</title>
      <link rel="icon" href="/assets/favicon.png" />
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
