// import { Geist, Geist_Mono, Comfortaa } from "next/font/google";
// import "./globals.css";
// import NavBar from "@/components/Navbar";
// import Footer from "@/components/Footer/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// const comfortaa = Comfortaa({
//   variable: "--font-comfortaa",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Kappes",

//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${comfortaa.variable} antialiased`}
//       >
//         <NavBar />
//         <div className="my-10 lg:px-32">{children}</div>
//         <Footer />
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono, Comfortaa } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer/footer";
import Providers from "@/components/Providers/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kappes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${comfortaa.variable} antialiased`}
      >
        <Providers>
          <NavBar />
          <div className="my-10 lg:px-32">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
